In [2]:
import pandas as pd

df = pd.read_csv('/Users/aoamacsplace/Documents/mosaic/Aave/token/data_copy.csv')

In [5]:


df['time_stamp'] = pd.to_datetime(df['time_stamp'], unit='s')
df = df.rename(columns={'time_stamp': 'DateTime'})

# Define value and time intervals along with corresponding scores as tuples
value_intervals = [(0, 1), (1, 10), (10, 100), (100, 1000), (1000, 10000), (10000, float('inf'))]
value_scores = [10, 25, 40, 55, 70, 100]

time_intervals = [(0, 30), (30, 90), (90, 180), (180, 365), (365, float('inf'))]
time_scores = [10, 30, 50, 70, 100]

# Create a function to calculate the score based on intervals and scores
def calculate_score(value, intervals, scores):
    for index, (start, end) in enumerate(intervals):
        if start <= value < end:
            return scores[index]
    return scores[-1]

# Assuming 'df' contains the original data as a DataFrame
# Create empty lists to store results
deposit_df, deposit_time_df, borrow_df, borrow_time_df, repayment_df = [], [], [], [], []

 
for address, group_data in df.groupby('From'):
    methods = group_data['Method'].unique()
    for method in methods:
        if 'depositETH' in method:
            value_in_eth = group_data['value'].sum()
            deposit_value_score = calculate_score(value_in_eth, value_intervals, value_scores)

            deposit_df.append({'Address': address, 'value': value_in_eth, 'Deposit Value Score': deposit_value_score})

            days_since_deposit = (pd.Timestamp.now() - pd.to_datetime(group_data['DateTime'])).dt.days
            deposit_time_score = calculate_score(days_since_deposit.iloc[0], time_intervals, time_scores)

            deposit_time_df.append({'Address': address, 'DateTime': group_data['DateTime'].iloc[0], 'Deposit Time Score': deposit_time_score})

        elif 'borrowETH' in method:
            value_out_eth = group_data['value'].sum()
            borrow_value_score = calculate_score(value_out_eth, value_intervals, value_scores)

            borrow_df.append({'Address': address, 'value': value_out_eth, 'Borrow Value Score': borrow_value_score})

            days_since_borrow = (pd.Timestamp.now() - pd.to_datetime(group_data['DateTime'])).dt.days
            borrow_time_score = calculate_score(days_since_borrow.iloc[0], time_intervals, time_scores)

            borrow_time_df.append({'Address': address, 'DateTime': group_data['DateTime'].iloc[0], 'Borrow Time Score': borrow_time_score})

        elif 'repayETH' in method:
            value_in_eth = group_data['value'].sum()
            repayment_value_score = calculate_score(value_in_eth, value_intervals, value_scores)

            repayment_df.append({'Address': address, 'value': value_in_eth, 'Repayment Value Score': repayment_value_score})


# Define the new intervals and scores for 'Borrow NA'
deposit_na_intervals = [(0, 1), (1, 2), (2, 3), (3, 10), (10, float('inf'))]
deposit_na_scores = [10, 30, 50, 70, 100]

# Create a function to calculate the score based on intervals and scores
def calculate_score(value, intervals, scores):
    for index, (start, end) in enumerate(intervals):
        if start <= value < end:
            return scores[index]
    return scores[-1]

# Assuming 'df' contains the original data as a DataFrame
# Create an empty list to store results
deposit_na_data = []

for address, group_data in df.groupby('From'):
    methods = group_data['Method'].unique()
    for method in methods:
        if 'depositETH' in method:
            # Count the number of different tokens Deposited (using unique token names)
            deposit_na_count = group_data['token_name'].nunique()
            deposit_na_score = calculate_score(deposit_na_count, deposit_na_intervals, deposit_na_scores)

            deposit_na_data.append({'Address': address, 'Deposit Token Score': deposit_na_score})

# Create a DataFrame from the list of dictionaries
deposit_na_df = pd.DataFrame(deposit_na_data)


# Define the new intervals and scores for 'Borrow NA'
borrow_na_intervals = [(0, 1), (1, 2), (2, 3), (3, 10), (10, float('inf'))]
borrow_na_scores = [10, 30, 50, 70, 100]

# Create a function to calculate the score based on intervals and scores
def calculate_score(value, intervals, scores):
    for index, (start, end) in enumerate(intervals):
        if start <= value < end:
            return scores[index]
    return scores[-1]

# Assuming 'df' contains the original data as a DataFrame
# Create an empty list to store results
borrow_na_data = []

for address, group_data in df.groupby('From'):
    methods = group_data['Method'].unique()
    for method in methods:
        if 'borrowETH' in method:
            # Count the number of different tokens Borrowed (using unique token names)
            borrow_na_count = group_data['token_name'].nunique()
            borrow_na_score = calculate_score(borrow_na_count, borrow_na_intervals, borrow_na_scores)

            borrow_na_data.append({'Address': address, 'Borrow Token Score': borrow_na_score})

# Create a DataFrame from the list of dictionaries
borrow_na_df = pd.DataFrame(borrow_na_data)


# Define the new intervals and scores for 'Borrow NA'
repay_na_intervals = [(0, 1), (1, 2), (2, 3), (3, 10), (10, float('inf'))]
repay_na_scores = [10, 30, 50, 70, 100]

# Create a function to calculate the score based on intervals and scores
def calculate_score(value, intervals, scores):
    for index, (start, end) in enumerate(intervals):
        if start <= value < end:
            return scores[index]
    return scores[-1]

# Assuming 'df' contains the original data as a DataFrame
# Create an empty list to store results
repay_na_data = []

for address, group_data in df.groupby('From'):
    methods = group_data['Method'].unique()
    for method in methods:
        if 'repayETH' in method:
            # Count the number of different tokens Borrowed (using unique token names)
            repay_na_count = group_data['token_name'].nunique()
            repay_na_score = calculate_score(repay_na_count, repay_na_intervals, repay_na_scores)

            repay_na_data.append({'Address': address, 'Repayment Token Score': repay_na_score})

# Create a DataFrame from the list of dictionaries
repay_na_df = pd.DataFrame(repay_na_data)

# Create DataFrames from the lists of dictionaries
deposit_df = pd.DataFrame(deposit_df)
deposit_time_df = pd.DataFrame(deposit_time_df)
borrow_df = pd.DataFrame(borrow_df)
borrow_time_df = pd.DataFrame(borrow_time_df)
repayment_df = pd.DataFrame(repayment_df)

# Merge all DataFrames on 'Address'
merged_df = deposit_time_df.merge(deposit_df, on='Address', how='outer')
merged_df = merged_df.merge(borrow_time_df, on='Address', how='outer')
merged_df = merged_df.merge(borrow_df, on='Address', how='outer')
merged_df = merged_df.merge(repayment_df, on='Address', how='outer')
merged_df = merged_df.merge(borrow_na_df, on='Address', how='outer')
merged_df = merged_df.merge(deposit_na_df, on='Address', how='outer')
merged_df = merged_df.merge(repay_na_df, on='Address', how='outer')
# Fill NaN values with 0
merged_df = merged_df.fillna(0)
merged_df.drop(columns = {'DateTime_x','value', 'DateTime_y', 'value_y'}, inplace = True)
merged_df = merged_df.rename(columns={'value_x': 'Value_in_ETH'})

KeyError: 'time_stamp'

In [6]:

merged_df.head()

,Address,DateTime_x,Deposit Time Score,value_x,Deposit Value Score,DateTime_y,Borrow Time Score,value_y,Borrow Value Score,value,Repayment Value Score,Borrow Token Score,Deposit Token Score,Repayment Token Score
0,0x00000001b01122945d67cf7c972f1a2063ca4008,2022-09-21 03:49:33,70.0,0.900037,10.0,0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0
1,0x00000009d94baf057697d988d2e3eec2fce81162,2022-09-21 03:50:03,70.0,0.200041,10.0,0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0
2,0x0000000a5d2afc64886a80780bc5ca6ecc519181,2022-09-09 03:35:03,70.0,0.300027,10.0,0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0
3,0x0000000f3a9e446d0a6f976df5f0ed1b324dcd0e,2022-09-09 03:35:03,70.0,0.200032,10.0,0,0.0,0.0,0.0,0.0,0.0,0.0,50.0,0.0
4,0x00000015e180b01c40b881e10774bc784bb6f4eb,2022-10-15 07:42:14,70.0,0.100000,10.0,0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0